-- AlterTable: add SEND_WEBHOOK to FlowStepAction enum
ALTER TABLE `FlowStep` MODIFY COLUMN `action` ENUM('REDIRECT', 'ASSIGN_TAG', 'MOVE_DEAL', 'CREATE_DEAL', 'SEND_EMAIL', 'SEND_WHATSAPP', 'SEND_WEBHOOK', 'UPDATE_CONTACT_STATUS', 'WAIT') NOT NULL;
